### ISSUE TITLE
PDFObject.embed won't be run

### ISSUE THREAD

**Issue by upupming** [lazypanda10117/docsify-pdf-embed#1]
Thanks for your plugin~

I have tested it for some time, and I find there is a problem with [this line](https://github.com/lazypanda10117/docsify-pdf-embed-plugin/blob/9fc43cf9fa1bfde372160279d91747f21029342e/src/docsify-pdf-embed.js#L73). 

The script is added to the html successfully:

![image](https://user-images.githubusercontent.com/24741764/48006397-538a3580-e150-11e8-9c65-124f1c0cf1aa.png)

But the script is not run, the code block is still code block:

![image](https://user-images.githubusercontent.com/24741764/48006438-669d0580-e150-11e8-9242-33491c68f606.png)

Did I miss any thing?

**Comment by lazypanda10117** [comment]
HI @upupming, have you included this line above importing my script?
```html
<script src="//cdnjs.cloudflare.com/ajax/libs/pdfobject/2.1.1/pdfobject.min.js"></script> 
```
Also, may I know what browser you are using? (Reason: if your browser doesn't inherently support pdf viewing (which is supported by firefox, chrome), it will automatically show the link as a fallback measure, as defined in the PDFObject.js)

Thank you for trying this out!

**Comment by upupming** [comment]
I'm using Chrome 70.0.3538.77 and I have tried replace 
```js
html += '<script>PDFObject.embed("'+ pdf_location +'", "#' + element_id +'")<\/script>'; 
```
with 

```
html += '<script>console.log('running script...')<\/script>'; 
``` 
but didn't get any message on the console tab.

You see [this demo](https://upupming.site/docsify-pdf-embed-plugin/docs/#/) and its [source code](https://github.com/upupming/docsify-pdf-embed-plugin/tree/master/docs).

**Comment by lazypanda10117** [comment]
I have looked briefly into this and ,for some reason, that specific pdf just dosen't work. I dont know why yet, so I will delve into that and get back to you in a day or two.

**Comment by lazypanda10117** [comment]
I think I have fixed the problem you've mentioned. Let me know if it works on your side!

**Comment by upupming** [comment]
Thanks, It works now! 

Follow your code, I found [executescript](https://github.com/docsifyjs/docsify/blob/master/docs/configuration.md#executescript) configuration now, this really tricky!
