### ISSUE TITLE
移动端自适应问题

### ISSUE THREAD

**Issue by RamblerW** [lazypanda10117/docsify-pdf-embed#4]
请问您有试过移动端吗？我用的时候发现移动端看不到pdf。
网址：https://ramblerw.github.io/blog-money/#/gupiao1/lesson/1020wanfenxiang
代码：https://github.com/RamblerW/blog-money/blob/master/gupiao1/lesson/1020wanfenxiang.md

**Comment by lazypanda10117** [comment]
When you view the page in mobile, it requires your mobile browser to inherently able to support pdf viewing (i.e. google chrome will not work). I will try to figure out a solution for that later this week. Thanks for pointing this out.

**Comment by lazypanda10117** [comment]
@RamblerW Sorry for this late reply. I have just gotten the time to investigate this problem and have implemented the feature requested above in version 1.0.6. If you are currently using this plugin, please let me know if the new version works for you. Thanks:D
