### ISSUE TITLE
Uncaught TypeError Prevents Loading of some Documents

### ISSUE THREAD

**Issue by maplion** [lazypanda10117/docsify-pdf-embed#8]
I'm not sure exactly what in the documents that don't load is preventing it from loading, but the following is the error I get:

```text
Uncaught TypeError: Cannot read property 'localeCompare' of undefined
    at pdf_renderer (docsify-pdf-embed.js:37)
    at renderer_func [as code] (docsify-pdf-embed.js:57)
    at u.tok (docsify.min.js:1)
    at u.parse (docsify.min.js:1)
    at Function.u.parse [as parser] (docsify.min.js:1)
    at docsify.min.js:1
    at docsify.min.js:1
    at ie.compile (docsify.min.js:1)
    at docsify.min.js:1
    at docsify.min.js:1
```

I was able to fix this by adding a truthy check on line 37 for the lang variable:

```js
if(!lang.localeCompare('pdf', 'en', {sensitivity: 'base'})){
```

TO

```js
if(lang && !lang.localeCompare('pdf', 'en', {sensitivity: 'base'})){
```

**Comment by lazypanda10117** [comment]
Do you mind providing me more context regarding this issue, in particular, the markdown file that relates to the pdf generation?  Currently, my assumption is there are some code blocks in the markdown files that are causing errors, possibly due to the language defined (or undefined) for those code blocks. My best guess is that there might be a code block above your `pdf` loading block and that code block has an empty declaration of language. For instance,

> \```(no language defined here)
> \```

Thanks for letting me know about this issue. I will fix it accordingly after I can exactly pinpoint where the error is.

**Comment by maplion** [comment]
@lazypanda10117  The pages that weren't loading were few and far between and had zero pdf-related stuff on them at all.  They were just long pages with lots of content, but nothing in particular that made them stand out from others.

**Comment by lazypanda10117** [comment]
@maplion My main concern is whether those pages have contents of this form. 
```
Some content here but the language of this code block is not defined
```
If so, then it makes sense to me how the truthy check resolves this issue. Otherwise, I will have to search for a different reason.

**Comment by maplion** [comment]
@lazypanda10117 Here's a copy of a non-proprietary document that consistently blows things up.  I haven't had time to dig into it to figure out exactly what causes it to blow up, but it still doesn't work 100% (sidebar and navbar blow up) with the pdf plugin enabled.

```md
# How to Extend the CodeBuild Environment

The CodeBuild environment is pretty robust and has most everything you need in it to get started.  Once you start trying to run Angular Tests in headless Chrome, however, you start running into issues with a lack of libraries.

You could add an `apt-get` command to the beginning of your buildspec.yml with all the necessary libraries and, in theory, this should work fine -- except that you're going to have to wait for those libraries to download and install every time your run a build.

In order to improve upon the speed of your builds, you need to extend the existing CodeBuild docker image and build your own image with the things you need it and then have CodeBuild use that image to start with instead of its managed image. (Note: CodeBuild Extension idea was given by this article: <https://aws.amazon.com/blogs/devops/extending-aws-codebuild-with-custom-build-environments/>)

## Angular Test Ubuntu Library Requirements

The following libraries are required to run Angular Tests in Headless Chrome (list acquired from here: <https://github.com/Googlechrome/puppeteer/issues/290>):

```text
# Need to be Added to CodeBuild Environment
gconf-service
libasound2
libatk1.0-0
libc6
libcairo2
libcups2
libdbus-1-3
libexpat1
libfontconfig1
libgcc1
libgconf-2-4
libgdk-pixbuf2.0-0
libglib2.0-0
libgtk-3-0
libnspr4
libpango-1.0-0
libpangocairo-1.0-0
libstdc++6
libx11-6
libx11-xcb1
libxcb1
libxcomposite1
libxcursor1
libxdamage1
libxext6
libxfixes3
libxi6
libxrandr2
libxrender1
libxss1
libxtst6
fonts-liberation
libappindicator1
libnss3
lsb-release
xdg-utils

# Already in CodeBuild Environment
ca-certificates
wget
```

## Canvas Requirements

For canvas, which libraries like protractor-image-comparison utilize, additional libraries are required:

```text
build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
```

Since the base image seems to have build-essential and libjpeg-dev already, these are the actual libraries added:

```text
libcairo2-dev libpango1.0-dev libgif-dev librsvg2-dev
```

## Global npm Library Requirements

The following are global installs that are required for the build that can be added to the environment to save time as well along with any additional serverless plugins, for example:

```shell
npm install -g @angular/cli serverless @aws-amplify/cli@multienv \
    serverless-cf-vars serverless-jest-plugin serverless-plugin-additional-stacks serverless-plugin-tracing \
    serverless-aws-documentation serverless-plugin-aws-alerts serverless-aws-alias serverless-dynamodb-local \
    serverless-pseudo-parameters serverless-reqvalidator-plugin serverless-s3-remover serverless-tag-api-gateway
```

## Adding Libraries to Dockerfile

First, you must find the link for the base CodeBuild image found in the list here: <https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html>.

Next, download the the files associated with that link, for example (node 10.14.1 image).

Then edit the Dockerfile.  In this case, the required libraries for headless chrome and puppeteer were added into the `apt-get install -y` list of libraries.  (Note: Ideally, I would have versions on the libraries, but I didn't take the time to figure out what versions were being pulled at this time).  Additionally, the npm install for the global libraries were added at the end.

These files were then committed for safe-keeping in the `gc-smartmap-deploy` repository within the vpc-for-docker-images project.

## Create Amazon ECR Repository

In the Amazon console, search for the service ECR, then "Create Repository" and give it a name.

### Give Permission to CodeBuild From Repository (ECR)

Once you have created a repository, click on it and then click on "Permissions" in the menu on the bottom left under Amazon ECR (<https://docs.aws.amazon.com/codebuild/latest/userguide/sample-ecr.html> #3 Principal).

Add a statement and Edit policy JSON and paste the following and then save :

```json
{
  "Statement": [
    {
      "Action": [
        "ecr:BatchGetImage",
        "ecr:BatchCheckLayerAvailability",
        "ecr:GetDownloadUrlForLayer"
      ],
      "Principal": {
        "Service": [
          "codebuild.amazonaws.com"
        ]
      },
      "Effect": "Allow",
      "Sid": "CodeBuildAccess"
    }
  ],
  "Version": "2008-10-17"
}
```

## Setting up an EC2 Instance with Docker

### Creating a VPC

While one could install docker locally and then perform the necessary actions to create an image, I decided to learn how to do it within the AWS ecosystem.

First, before one can launch an ec2 instance, one needs a vpc that they can launch it in.  I created a serverless.yml file that spins up the majority of necessary VPC components within the `gc-smartmap-deploy` repository in the vpc-for-docker-images project.  If not already deployed (or torn down), with a terminal open within the vpc-for-docker-images directory, deploy the stack using serverless with:

```shell
sls deploy --stage=dev
```

### Launching the EC2 Instance

Open up the Amazon Console and go to the EC2 Dashboard.  Make sure you're in the correct region (e.g. us-east-1) and click the "Launch Instance" button.

Launch Wizard Page 1:
Choose an Amazon Linux 2 AMI (64-bit x86).

Launch Wizard Page 2:
Choose t2.micro (or choose bigger if you desire to make things go a bit faster).

Launch Wizard Page 3:
Choose the:

1. VPC (e.g. gc-smartmap-deploy-vpc)
2. The public subnet (e.g. gc-smartmap-deploy-public-subnet1)
3. <span style="color:green;">Update:</span> choose Auto-assign Public IP: Enable and the Elastic IP step can be skipped.

Launch Wizard Page 4:
Just go next.

Launch Wizard Page 5:
Add tags:
    - Department: Joint Ops
    - Software: Smart Map
    - Customer: GeoComm

Launch Wizard Page 6:
Select an existing security group and check the one with TCP port 22 open (e.g. gc-smartmap-deploy-functions-dev-securityGroup-XXXXXXXX)

Launch Wizard Page 7:
Review and launch the instance.  Choose your keypair file if you have one and acknowledge that you have it; otherwise, click create new keypair and download the .pem file and store it somewhere secure on your local drive that you can easily find it (e.g. `c:\aws\my-key.pem`)

Click "View instances" to go back to the EC2 Dashboard running instances page.

### Create Elastic IP

>[!TIP]
>You do not need to do this if you auto-assigned a Public IP in page 3 of the EC2 Launch Wizard

On the left menu of the EC2 Dashboard, under "NETWORK & SECURITY" choose Elastic IPs.  Click the "Allocate new address" button, leave it on the default of "Amazon pool" and click "Allocate".

Note the IP address that is allocated for future use (save in notepad or something).

### Associate Elastic IP

Once the new Elastic IP is provisioned, select it and click Actions > Associate Address.  Leave the Resource type on the default of "Instance" and then choose the ec2 instance that was just launched.  Then click "Associate".

### Connect to EC2 instance

Assuming you're on Windows and using Windows Subsystem for Linux (WSL) and Ubuntu Application 18.04 (please see the [WSL section here if you need assistance](developer-software-setup/computer_software_setup.md), open the Ubuntu 18.04 Application and type the following (note: all Windows files are found within `/mnt/c/` and xxx.xxx.xxx.xxx is the Elastic IP that was created):

- `cd /mnt/c/aws`
- `sudo ssh -i "my-key.pem" ec2-user@xxx.xxx.xxx.xxx`

>[!DANGER]
>if you do not use sudo, it will tell you that your key is too open; normally you could fix this with a `chmod 400 my-key.pem`, but that doesn't really work in Windows.

You may be asked for your sudo password; enter your master linux password and then you may be asked if you're sure you want to connect, just type y and press enter.

Now you're connected and at the EC2 instance console.  At this point run the following commands (<https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-basics.html>):

- `sudo yum update -y`
- `sudo yum install docker -y`
- `sudo service docker start`
- `sudo usermod -a -G docker ec2-user`

This can also be all done on a single line:

```shell
sudo yum update -y && sudo yum install docker -y && sudo service docker start && sudo usermod -a -G docker ec2-user
```

Log out with `exit` and then ssh log back in (you can recall your previous command with up-arrow).

Run `docker info` to check if your instance has the right permissions for the Docker daemon.

## Create Docker Image

### Create Docker Files

Type `vi Dockerfile` and then when inside vi, press `i` to enter insert mode and then go to the Dockerfile that was created earlier and right-click copy and then right-click inside the opened file within vi and it should paste.  Then hit escape to get out of insert mode and then type `:x` for save and exit and hit enter.

Use the same method to copy over the other two files `vi dockerd-entrypoint.sh` and `vi ssh_config`.

### Configure AWS

You need to give the aws cli your permissions to be able to utilize it, so type `aws configure` and then give it your ID and SecretID (acquired as programmatic keys to your account; may need Ryan Dammrose or someone from IT Support to get them for you if you do not have them) and set the default region (e.g. us-east-1).

### Connect AWS ECR to Docker

You need to use the aws cli to connect the Container Repository to the docker instance by running the following:

```shell
$(aws ecr get-login --no-include-email --region us-east-1)
```

### Build the Docker Image

It will take a long time to build the docker image and you'll see a lot of red go across the screen, but unless it exits with something other than a zero, you should be good.  I did have to run it a couple of times due to GPG key retrieval issues, which I don't entirely understand, but re-running seemed to resolve.

To create your build (don't forget the period):

```shell
docker build -t gc-smartmap-build .
```

### Tag your Docker Image

```shell
docker tag gc-smartmap-build:latest 709177336629.dkr.ecr.us-east-1.amazonaws.com/gc-smartmap-build:latest
```

### Push your Docker Image

```shell
docker push 709177336629.dkr.ecr.us-east-1.amazonaws.com/gc-smartmap-build:latest
```

## Point CodeBuild to Custom Image

Once you have successfully pushed your image into the Amazon ECR Repository and CodeBuild has permissions to use it, you can set CodeBuild up to point to it by going to the build project, clicking "Edit" in the upper right and choosing "Environment".

Within Environment, click "Override image", choose "Custom image", choose Environment type "Linux", choose "Amazon ECR", choose "My ECR account", then choose your repository name and the repository image name.  Then click "Update Environment".  Note: if you're using your own service role, uncheck the "Allow AWS CodeBuild to modify this service role so it can be used with this build project" -- you may get an error if you do not.

## Angular Project Considerations for Karma and Protractor

### Separate ci configurations for Karma and Protractor

Since the ci stuff needs to run in headless Chrome, it requires different configuration files for both karma and protractor that must be called with proper flags.

### Example package.json scripts

```json
"scripts": {
    "test-ci": "ng test --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox --karma-config=src/karma-ci.conf.js",
    "e2e-ci": "ng e2e --protractor-config=e2e/protractor-ci.conf.js",
    ...
}
```

### Example karma-ci.conf.js

```javascript
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html
const puppeteer = require('puppeteer');
process.env.CHROME_BIN = puppeteer.executablePath();

module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular-devkit/build-angular'],
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage-istanbul-reporter'),
            require('@angular-devkit/build-angular/plugins/karma')
        ],
        client: {
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        coverageIstanbulReporter: {
            dir: require('path').join(__dirname, '../coverage'),
            reports: ['html', 'lcovonly', 'text-summary'],
            fixWebpackSourcePaths: true
        },
        reporters: ['progress', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Chrome'],
        customLaunchers: {
            ChromeHeadlessNoSandbox: {
                base: 'ChromeHeadless',
                flags: ['--no-sandbox']
            }
        },
        singleRun: false
    });
};

```

### Example protractor-ci.conf.js

```javascript
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

const {
    SpecReporter
} = require('jasmine-spec-reporter');
const puppeteer = require('puppeteer');

exports.config = {
    allScriptsTimeout: 11000,
    specs: [
        './src/**/*.e2e-spec.ts'
    ],
    capabilities: {
        browserName: 'chrome',
        chromeOptions: {
            args: ['--headless', '--no-sandbox'],
            binary: puppeteer.executablePath()
        }
    },
    directConnect: true,
    baseUrl: 'http://localhost:4200/',
    framework: 'jasmine',
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000,
        print: function () {}
    },
    onPrepare() {
        require('ts-node').register({
            project: require('path').join(__dirname, './tsconfig.e2e.json')
        });
        jasmine.getEnv().addReporter(new SpecReporter({
            spec: {
                displayStacktrace: true
            }
        }));
    }
};

```

### Example buildspec.yml additions

```yaml
...
  build:
    # run-as: Linux-user-name
    commands:  
      - echo ** Run Angular Build **
      - echo Build started on `date`
      - ng build --prod --aot --configuration=${BUILD_ENV}
      - echo ** Run Angular Tests **
      - export CHROME_BIN=/usr/bin/chromium-browser
      - npm run test-ci
      - echo ** Run e2e Tests **
      - npm run e2e-ci  
...
```

## Run CodeBuild and Test

If you made it this far, then you can finally test the fruits of your labor.  If all goes well, your angular tests will run as part of your build.

## Cleanup

The EC2 instance should be taken down as it will charge for just existing.  The same goes for the generated Elastic IP (when not attached to an instance).  The VPC can be taken down if you choose or can be left in place for other EC2 attachments.
```

**Comment by lazypanda10117** [comment]
@maplion I have found out which section of the markdown is causing the error, but I am not sure of the reason yet. Will update you later. In the meantime, this is the section that is blows everything up:(
```md
Launch Wizard Page 5:
Add tags:
    - Department: Joint Ops
    - Software: Smart Map
    - Customer: GeoComm
```

**Comment by lazypanda10117** [comment]
@maplion The reason of the error is that I haven't taken `[tab] as code block` into account. The formatting you have above is actually a code block instead of a list (although I am not sure if that is your intention). As I have pointed out above, I forgot to take care of the empty language declaration case (in this case, the tab code block doesn't even support language declaration), which is the reason for all these errors. I will fix this later today and please let me know if it fixes your issue. Thanks!

**Comment by maplion** [comment]
Great, thanks for letting me know.  Glad to help.

**Comment by lazypanda10117** [comment]
It should be fixed now. You might need to clear cache before it takes effect.

**Comment by maplion** [comment]
Yup, that fixed it.  Thanks again!
