### ISSUE TITLE
No pdf 

### ISSUE THREAD

**Issue by Phil795** [lazypanda10117/docsify-pdf-embed#9]
Today I have integrated the plugin. Current version.
I have integrated pdfobject.min.js and docsify-pdf-embed.js after docsify.min.js in the index.html

All scripts are found.

But the PDF is not loaded. I see a codeblock with the content `pdf pdf/jaspersoft-studio-user-guide_9.pdf `

There is no console output. How can I debug this kind of problem?

Here is my markdown
# Benutzerhandbuch
-------------------------------

​```pdf
   pdf/user-guide_2.pdf
​```

**Comment by lazypanda10117** [comment]
Hi @Phil795, 

Thanks for letting me know of this issue and for using the plug-in. With some testing, it seems to me that the ------- line is causing the problem, but I am not sure what the exact reason is yet. I will look into it and get back to you later this week.

- Jeff

**Comment by Phil795** [comment]
Hello @lazypanda10117,

thanks for your quick feedback.
Removed the sign, now the PDF display works :D 

When I copy the lines from the readme into my .md file, the error occurs. Maybe you can adjust the Readme so that Copy'n'Paste works.... or the error occurs only with me >.<

**Comment by lazypanda10117** [comment]
It has been long since I first wrote this plug-in. It appears that I put the zero-width space there for the styling. I have updated the readme and hopefully it is now clearer : )
